### ISSUE TITLE
Add icon in manifest.json

### ISSUE THREAD

**Issue by IgorRozani** [IgorRozani/bate-palmas#7]
Add a icon image similar to the [favicon](https://github.com/IgorRozani/bate-palmas/blob/master/favicon.ico) in manifest.json for the sizes 48x48, 96x96 and 192x192.

**Comment by gayankalhara** [comment]
Going to do this now.

**Comment by Ridermansb** [comment]
> Going to do this now.

Working on this now

**Comment by IgorRozani** [comment]
Issue solved in  PR #11 and #8
